### ISSUE TITLE
Reading *.xlsx file reports zip format error

### ISSUE THREAD

**Issue by lukiinc** [catamphetamine/read-excel-file#10]
I've tried reading an xlsx file from my nodejs console application and I am getting a weird error that I cannot resolve. Code is the following:
`
const readExcelFile = require('read-excel-file');
var readstream = fs.createReadStream(fileName);
readExcelFile(readstream).then((rows) => {
         console.log(rows);
});
`
The error is the following:
![image](https://user-images.githubusercontent.com/23029992/46567957-84066600-c93d-11e8-8d3c-e4934800d7b0.png)

I've also tried reading the xlsx file directly:
`
readExcelFile(somepath).then((rows) => {
         console.log(rows);
});
`
I get the following error:
![image](https://user-images.githubusercontent.com/23029992/46567970-e2cbdf80-c93d-11e8-9029-99937b9979f0.png)

I hope someone can help... Thank you :)

**Comment by catamphetamine** [comment]
Seems to be some issues with reading the file. Don’t know.

**Comment by atlewee** [comment]
This also happens to me if I use the browser version in node.
This error goes away over here if I use the node version:
const readExcelFile = require('read-excel-file/node')

**Comment by catamphetamine** [comment]
@atlewee 
Indeed, there's `JSZip` stack trace in the console which means that the browser version is being used in Node.
Closing then.
