### ISSUE TITLE
Running in Web Workers

### ISSUE THREAD

**Issue by jgsoftw** [catamphetamine/read-excel-file#100]
Is it possible to select to use XMLDOM.DOMParser() instead of Document DOMParser in Browser?. This is for using it in Web Workers.

**Comment by catamphetamine** [comment]
> This is for using it in Web Workers.

Published `read-excel-file@5.2.22`.
Use `/web-worker` export.

**Comment by jgsoftw** [comment]
Thanks for adding it, just small issue found, the index in /web-worker is still pointing to node version.
export { default as default } from '../modules/read/readXlsxFileNode'

**Comment by catamphetamine** [comment]
@jgsoftw Indeed, published `read-excel-file@5.2.23`

**Comment by jgsoftw** [comment]
Thanks Nikolay, I just got another issue, the d.ts in the web worker  has:
export * from '../index.d';
This doesn't export default. so, using typescript in the import we have to import function by name.
import {readXlsxFile} from 'read-excel-file/web-worker'

But importing by name, is sending me an error with webpack.
TypeError: (0 , read_excel_file_web_worker__WEBPACK_IMPORTED_MODULE_2__.readXlsxFile) is not a function

If in the .d.ts is the full definition to expose export default. it works perfect.
By the way, using it in web worker, I'm reading a file with 100k rows 2 columns in around 10s.

import {
	ParseWithSchemaOptions,
	ParseWithMapOptions,
	ParseWithoutSchemaOptions,
	ParsedObjectsResult,
	Row
} from '../types.d';

export function parseExcelDate(excelSerialDate: number) : typeof Date;

type Input = File;

export function readXlsxFile<T extends object>(input: Input, options: ParseWithSchemaOptions<T>) : Promise<ParsedObjectsResult<T>>;
export function readXlsxFile<T extends object>(input: Input, options: ParseWithMapOptions) : Promise<ParsedObjectsResult<T>>;
export function readXlsxFile(input: Input, options?: ParseWithoutSchemaOptions) : Promise<Row[]>;

export default readXlsxFile;

**Comment by catamphetamine** [comment]
@jgsoftw Hmm, I see...
Published `read-excel-file@5.2.24`

**Comment by jgsoftw** [comment]
Thank you so much, it's working perfect now.
