### ISSUE TITLE
Date values are not returned the same from a cell with the format mm/dd/yyyy

### ISSUE THREAD

**Issue by sgnark** [catamphetamine/read-excel-file#109]
I am facing a issue with the date values. 
 In a cell I am having a date value with the format mm/dd/yyyy. While reading the excel file the value returned is one day lesser than the value in the cell. 
 
Example: the cell is having 4/30/2017, the returned value from the cell is "Sat Apr 29 2017 19:00:00 GMT-0500 (Central Daylight Time)"

can you please review and confirm is this existing issue or there is a configuration which I missed. 

Note: while reading the excel I am even the format as mm/dd/yyyy passed or not, the issue exists.

**Comment by catamphetamine** [comment]
That is the correct behavior: the date is correct in UTC+0 time zone.

**Comment by sgnark** [comment]
Hi, 

in the browser console its printing as for the cell value "Sat Apr 29 2017 19:00:00 GMT-0500 (Central Daylight Time)"

if its UTC then it should return the value as UTC format ? 

I am in the time zone as GMT-0500 (Central Daylight Time) but the value is alone different. Why is it so ?

**Comment by catamphetamine** [comment]
No. It prints correctly

**Comment by sgnark** [comment]
Sorry Still I am not understanding it correctly. 

I have a cell value as 4/30/2017 with the format as DD/MM/YYYY 

what is the return value ? how it should print ?
