### ISSUE TITLE
Dates with time included don't get parsed with the Date type using a schema

### ISSUE THREAD

**Issue by KellyWebServices** [catamphetamine/read-excel-file#11]
If I have a date and time combined field in my spreadsheet with the data & time format that excel provides, the date portion only gets parse to my JSON.

Example: 1/16/2018  7:30:00 PM
Parsed without using schema: 43141.8125
Parsed with schema and column as Date: 2018-02-10T12:00:00.000Z

Any thoughts on adding the time parsing to the Date type or even a separate Time schema type if easier? Otherwise things have been working well, thanks!

**Comment by catamphetamine** [comment]
Hmm, I see, time then.
Actually, I'd prefer it parsing without schema given that it's a standard Excel date/time format as you say.
See this piece of code:
https://github.com/catamphetamine/read-excel-file/blob/37394b4bf23e27e914d50ac750bb589b812c3d98/source/readXlsx.js#L173
It looks at `style.numberFormat.id`.
Go to your `node_modules/read-excel-file/<dir>/readXlsx.js` and add a `console.log()` there to find out which number format is set for your date/time column values.
`<dir>` is either `commonjs` or `module`.

**Comment by SiTingST** [comment]
Hi, I'm facing the same issue as well. May I know what's the code to find out which number format is set for my date/time column value? I have attached a sample of my excel file along with this comment. I would like to get back the same date (3/11/2018) and same start and end time (11:00, 13:00). Thank you >< 
[eg1.xlsx](https://github.com/catamphetamine/read-excel-file/files/2544624/eg1.xlsx)

**Comment by catamphetamine** [comment]
@SiTingST 
What are the expected parsed values?
Currently it gives:

```json
[ [ 'Number',
    'Place',
    'Postal Code',
    'Date',
    'Start Time',
    'End Time' ],
  [ 1,
    'ABC',
    1903-01-15T12:00:00.000Z,
    2018-11-03T12:00:00.000Z,
    '11:00am',
    '12:00pm' ] ]
```

**Comment by SiTingST** [comment]
My expected parsed value would be 
integer for number and postal code column, string for place column and a dd/mm/yy format (04/11/2018) for date column without the time. As for start and end time, the format to be as 11:00am.

**Comment by catamphetamine** [comment]
So it parses everything correctly then.
It also parses "Postal code" as a date and so does PlanMaker.
So seems that your Excel software sets "Postal code" format incorrectly.

![image](https://user-images.githubusercontent.com/477167/47959475-49542400-dff6-11e8-8e66-0594059eeb76.png)
