### ISSUE TITLE
Accessing other row values in custom validation

### ISSUE THREAD

**Issue by MachariaK** [catamphetamine/read-excel-file#112]
I want to access other row values when validating data. Is this possible? See code below:

`const schema = {
    'KRA Pin': {
        prop: 'kraPin',
        required: true,
        type: (value, row) => {
            console.log(row) // HOW CAN I ACCESS nssfNUMBER HERE?
        }
    },
    'NSSF Number': {
        prop: 'nssfNumber',
        required: true,
    },
}`

**Comment by catamphetamine** [comment]
Hi. There’s no support for such validation in the library. That type of
complex validation could be done after parsing data.

**Comment by Deepakeon** [comment]
Hi, if we do the validation after parsing data, how to get the row number and column name in which the validation failed?

**Comment by catamphetamine** [comment]
The errors list items have row and column indexes
