### ISSUE TITLE
String/numbers are parsed as date despite schema type being a string.

### ISSUE THREAD

**Issue by UsmanNadeem** [catamphetamine/read-excel-file#115]
The data looks like this: `11-2021`, `45-2092` etc. This is not supposed to be a date, but codes for something.

I have a schema with `type: String`
Reading like this:
```
const MySchema = {
  ITEM_CODE: {
    prop: "ITEM_CODE",
    type: String,
  },
  ...
}
readXlsxFile(".....xlsx", {
    schema: MySchema,
    dateFormat: "yyyy/mm/dd",
  });
```
I get the following error:

```
Error: "invalid". 
Reason: "not_a_string". 
Value: "Mon Nov 01 2021 00:00:00 GMT+0000 (Coordinated Universal Time)".

```

**Comment by catamphetamine** [comment]
Excel automatically converts those strings to dates when you input them

**Comment by UsmanNadeem** [comment]
I see that excel converted the data into dates after I manually edited the sheet, the original document has those in text form (which reads fine now that I try to read it).
