### ISSUE TITLE
How to list the existing sheets ?

### ISSUE THREAD

**Issue by redanium** [catamphetamine/read-excel-file#14]
Is there a way to get an array of the sheets' names ?

**Comment by catamphetamine** [comment]
Why would you need that?

**Comment by redanium** [comment]
implementing tabs of sheets

**Comment by catamphetamine** [comment]
I still don't see why would you need to get the names of the sheets.
You can provide a more concrete example.

**Comment by catamphetamine** [comment]
Released `read-excel-file@2.0.6`.
Pass `getSheets: true` option.
See the README for more info.

**Comment by redanium** [comment]
Thanks dude :+1:
