### ISSUE TITLE
Columns with duplicate names get mangled

### ISSUE THREAD

**Issue by tutordelphia** [catamphetamine/read-excel-file#16]
I am reading in Excel files where the schema is not known ahead of time and column names may be duplicated. 

Currently, if there are two columns named "Category" the values for the second "Category" column get shown for both columns. The behavior I'd like is to have the option of renaming any duplicates as ColumnName_1 and ColumnName_2. Is that possible currently without knowing which columns will be duplicated in advance?

**Comment by catamphetamine** [comment]
Why do they have duplicate columns?

**Comment by tutordelphia** [comment]
That's how our clients send us the data and we don't have the ability to change the format of the Excel files.

**Comment by catamphetamine** [comment]
I guess they shouldn't introduce duplicates then.
You can check for duplicates by examining the first row.
If there are duplicate column titles then you display an error.

**Comment by tutordelphia** [comment]
On the backend we are handling it with Pandas so I'm trying to match the behavior Pandas shows with duplicates: 

mangle_dupe_cols : boolean, default True

From https://pandas.pydata.org/pandas-docs/version/0.21/generated/pandas.read_csv.html
Duplicate columns will be specified as ‘X.0’...’X.N’, rather than ‘X’...’X’. Passing in False will cause data to be overwritten if there are duplicate names in the columns.

**Comment by catamphetamine** [comment]
> The Excel files get used in multiple automated systems so changing the files to remove duplicates isn't really an option.

I guess if the file is not supposed to contain duplicates then it shouldn't contain duplicates.
Otherwise it's an invalid file.
For a developer it's easier if users format their files correctly than to fix their errors for them.

**Comment by tutordelphia** [comment]
Gotcha, I understand if this is a "won't fix" for you. In our use case, we are supposed to get the files as we get them and then clean them up as we need once they've been uploaded. I may be able to pass the file off to our backend where handling these duplicates is already implemented and then pass something clean back to the frontend which will cut out our need to use a frontend Excel package along with a backend one.

**Comment by catamphetamine** [comment]
Or, you can copy the `src` folder to your project and inside `convertToJson()` alter the data in order to rename the columns.
https://github.com/catamphetamine/read-excel-file/blob/master/source/convertToJson.js#L18

**Comment by tutordelphia** [comment]
Gotcha, that may be a good option. Thanks again.

**Comment by catamphetamine** [comment]
Another alternative is to use such code:

```js
import { readXlsx, convertToJson } from 'read-excel-file'

const result = readXlsx(file, { properties: true })
result.data = handleDuplicateColumns(result.data)
return convertToJson(result.data, schema, { properties: result.properties })
```

`convertToJson` is available in `read-excel-file@2.0.7`.

**Comment by tutordelphia** [comment]
That worked, thanks! We ended up modifying this function to change the duplicates and the rest as you suggested: https://stackoverflow.com/questions/10643933/renaming-duplicates-in-javascript-array

**Comment by catamphetamine** [comment]
```js
import readXlsxFile from 'read-excel-file'

readXlsxFile(file, {
  schema,
  transformData(data) {
    return data
  }
})
```
