### ISSUE TITLE
Generate Dynamic Schemas

### ISSUE THREAD

**Issue by timratha** [catamphetamine/read-excel-file#18]
Hi, I am working around in a way where i could have dynamic column. Is there any way to just get columns ?

**Comment by catamphetamine** [comment]
Provide an example of what's the issue you're having

**Comment by timratha** [comment]
we would like to read excel data and keep the format exactly the same as the excel file. Then the problem we have is when data is date format, the data is converted to this weird number like the picture below.

![image](https://user-images.githubusercontent.com/6808523/53714465-16754c00-3e81-11e9-8646-8ecbdb063dc8.png)

**Comment by catamphetamine** [comment]
Parsing dates is done in this code:
https://github.com/catamphetamine/read-excel-file/blob/e8de62a32afaf3d0fda7989e17e3b320c8c61622/source/readXlsx.js#L184-L194

Dates not always can be autodetected.
You can `console.log()` there and see what format are your dates in and pass it as `options.dateFormat`.
