### ISSUE TITLE
Can't run in browser with Angular / Type Script / Webpack

### ISSUE THREAD

**Issue by emmanueldaher** [catamphetamine/read-excel-file#20]
Hello folks,
I'm using version 2.0.7 with Angular 7.2.0 and jszip@~3.1.5 according to the packae.json dependencies, although I can't even build in dev mode.
Here is the error message:

**ERROR in ./node_modules/jszip/lib/readable-stream-browser.js
Module not found: Error: Can't resolve 'stream' in '...\node_modules\jszip\lib'**

Does someone know whats is going on?

----
Update: I've tried to reproduce the error on stackblitz and then i got another error:
https://stackblitz.com/edit/angular-5tbb8h?file=src%2Fapp%2Fxls-reader%2Fxls-reader.component.ts

**Comment by catamphetamine** [comment]
@emmanueldaher The error comes from `jszip` package.
Something like this one:
https://github.com/Stuk/jszip/issues/524
You can report the error in their repo.

**Comment by nternouski** [comment]
whats is the solution for that? I have the same issues.

**Comment by renilbabu03** [comment]
`npm install stream` worked for me

**Comment by radiumrasheed** [comment]
I think `stream` should just be added as a peer dependency
