### ISSUE TITLE
fails to open xlsx created by .net epplus

### ISSUE THREAD

**Issue by Alex-Ifax** [catamphetamine/read-excel-file#21]
Hi!

trying to open file creаted by .net epplus (epplus_fail.xlsx) - but it fails
if file open with ms office and save (ms_office_saved_ok.xlsx) - it will be readed ok.

files example in attach
[epplus_fail.xlsx](https://github.com/catamphetamine/read-excel-file/files/3010176/epplus_fail.xlsx)
[ms_office_saved_ok.xlsx](https://github.com/catamphetamine/read-excel-file/files/3010180/ms_office_saved_ok.xlsx)

Thanks.
Alex

**Comment by catamphetamine** [comment]
It was a weird bug: it didn't parse XML because it wasn't trimmed.
Fixed in `read-excel-file@2.0.9`.

**Comment by Alex-Ifax** [comment]
great, thanks!
