### ISSUE TITLE
TypeError: Cannot read property 'trim' of undefined

### ISSUE THREAD

**Issue by mswpac** [catamphetamine/read-excel-file#22]
When attempting to read this file, I receive the error in the title.

readXlsxFile(target.files[0], { dateFormat: "DD/MM/YYYY" }).then(rows => {
console.log(rows);
});

[Settlement Dates.xlsx](https://github.com/catamphetamine/read-excel-file/files/3062395/Settlement.Dates.xlsx)

**Comment by catamphetamine** [comment]
Released `read-excel-file@2.0.10` with the fix.
