### ISSUE TITLE
Not able to find Sheets by name

### ISSUE THREAD

**Issue by venkatrv** [catamphetamine/read-excel-file#23]
I have excel sheet by name sheet 1.
I am trying to read the sheet 1 with the code:
readXlsxFile(input.files[0], { sheet: 'sheet 1'}).then(function (data) { }
and I am getting the following error. Not sure I am using the API correctly. Could you please check it?

> Error: Sheet "sheet 1" not found in *.xlsx file. Available sheets: "Detail" (#11), "Header" (#12), "sheet 1" (#13)

**Comment by catamphetamine** [comment]
Use `console.log()` to see why the error is thrown.
https://github.com/catamphetamine/read-excel-file/blob/cabd7e117f89635b6b22593eb751aa4021a66b2f/source/readXlsx.js#L45

**Comment by venkatrv** [comment]
i did the console.log, that's how I shared the error:
Error: Sheet "sheet 1" not found in *.xlsx file. Available sheets: "Detail" (#11), "Header" (#12), "sheet 1" (#13)
Any idea why it is showing sheet 1 as  "sheet 1" (#13) ? what does the #13 means here?

**Comment by catamphetamine** [comment]
> i did the console.log, that's how I shared the error:

Add console.log to the file I linked in my previous comment in `node_modules` to see what happened.
# 13 is the ID of the sheet.

**Comment by catamphetamine** [comment]
See if version `3.0` works.
It didn't address this specific issue but some code was changed and maybe as a side effect your issue disappeared.
