### ISSUE TITLE
Referencing a worksheet by name or id does not work

### ISSUE THREAD

**Issue by femto11** [catamphetamine/read-excel-file#24]
I think the problem (and i have checked that on two of my workbooks) is that in the xlsx bundle the worksheets are indexed by their position on the tab (eg. ./xl/worksheets/sheet2.xml contains the 2nd sheet on the tab). In the library instead the id of the sheet from the workbook.xml is beeing used to index the worksheet file. 

Unfortunately I don't see a workaround because readXlsx with option 'getSheets' returns a hash that is ordered by the worksheet id and this the index is lost.

**Comment by catamphetamine** [comment]
Provide an example, otherwise it's not clear what you mean.

**Comment by femto11** [comment]
I can give you some steps to reproduce:

1.  Create an Excel workbook with 3 worksheets. 
2. In the first fill in the cell A1, in the 2nd cells a1 and b1, and in the 3rd celll a1, b1, c1
3. Save the workbook
4. make a copy of the workbook and rename the file to .zip.
5. Open the archive, and view the file xl/workbook.xml.
    You should see something like this somewhere:
```
<sheets>
<sheet r:id="rId1" sheetId="1" name="Tabelle1"/>
<sheet r:id="rId2" sheetId="2" name="Tabelle2"/>
<sheet r:id="rId3" sheetId="3" name="Tabelle3"/>
</sheets>
```
6. Now go to ./xl/worksheets and look into the 3 SheetN.xml files. File 1 will have one filled cell, 2 two, and so on.
7. Go back to the Excel and alter the order of the sheets on the sheet tab at the bottom. Let's say move sheet 3 to position one.

Now repeat steps 3 - 6:
The workbook.xml now should show something like this:
```
<sheets>
<sheet r:id="rId3" sheetId="3" name="Tabelle3"/>
<sheet r:id="rId1" sheetId="1" name="Tabelle1"/>
<sheet r:id="rId2" sheetId="2" name="Tabelle2"/>
</sheets>
```
And i.e. the file xl/worksheets/Sheet1.xml should have 3 cells filled in, so it is clearly what we called Tabelle3 but it is now sheet number one. This show that the number N in the filenames of the SheetN.xml files denotes the order of the file on the tab and not the sheetId found in the /xl/workbook.xml file.

**Comment by femto11** [comment]
Ah, maybe I shall add that the code in the library uses the sheeId to build the filenames for the sheet files while it should use their index (i.e. position) in the sheets enemeration found in the xl/workbook.xml file.

**Comment by catamphetamine** [comment]
Well, seems like you’re talking about “indexes” here, not “names” or “ids”, so the library behaves as expected.
What you requested is a new feature of reading a sheet by "index" rather than "id".

**Comment by femto11** [comment]
Don't worry. I cloned the repo and I'm going to fix it myself. Thank you.

**Comment by catamphetamine** [comment]
There's `excel_mac_2011-basic.xlsx` in the `test` directory.
I created a copy of it — `excel_mac_2011-basic - Copy.xlsx` — and added a new sheet "Sheet2" and moved it to the first position.
Then I ran `npm test` and it said that sheet # 1 (the default one) has incorrect data.
Which means that when sheets are reordered then their IDs change.
I used "Plan Maker" for editing Excel sheets.

**Comment by femto11** [comment]
As you might have seen in the example I described above the id's don't change. It's the position in the list that changes and of course the name of the sheet files. I provided a fix in my fork already, yet untested. But you can see my changes there. I think it is really a defect in the library.,

**Comment by femto11** [comment]
And recently someone reported an issue (#23) here pointng to the same problem.

**Comment by catamphetamine** [comment]
Ok, see if version `3.0` works.
