### ISSUE TITLE
How to skip rows

### ISSUE THREAD

**Issue by andreanta** [catamphetamine/read-excel-file#27]
I have a excel file with a header rows before the data, ho can i skip the first rows?
I use json schema mapping.

Thanks
Andrea Del Brocco

**Comment by catamphetamine** [comment]
```js
import readXlsxFile, { convertToJson } from 'read-excel-file'

const result = readXlsxFile(file, { properties: true })
result.data = addHeaderColumns(result.data)
return convertToJson(result.data, schema, { properties: result.properties })
```

**Comment by andreanta** [comment]
I've tried with this solutions but maybe i'm not explain problem well.
I have a file xslx with some row (first 4 rows) that contains header text not column names or data
The header of the data and the data itself begin at row 5.
If i try to read an excel file with the library i have no data.

So how can i begin to read data and columns from a certain row ?

TIA
Andrea

**Comment by catamphetamine** [comment]
> So how can i begin to read data and columns from a certain row ?

```js
import readXlsxFile, { convertToJson } from 'read-excel-file'

const result = readXlsxFile(file, { properties: true })
result.data = skipNRows(result.data)
return convertToJson(result.data, schema, { properties: result.properties })
```

**Comment by andreanta** [comment]
I upload a sample excel file, if i try to open the file the result object
contains no data

Il giorno ven 24 mag 2019 alle ore 02:02 Nikolay <notifications@github.com>
ha scritto:

**Comment by andreanta** [comment]
If i remove the first rows and upload the same xlsx with columns and rows
in the header the object obviously is ok

Il giorno ven 24 mag 2019 alle ore 11:44 andrea del brocco <
a.delbrocco@gmail.com> ha scritto:

**Comment by catamphetamine** [comment]
If you paste a link to an online demo I could take a look.

**Comment by andreanta** [comment]
[Partecipazioni_14_04_2019_gara_tipologia_60_track_organizzata_da_04gcat_club_arcieri_treviglio.xlsx](https://github.com/catamphetamine/read-excel-file/files/3216626/Partecipazioni_14_04_2019_gara_tipologia_60_track_organizzata_da_04gcat_club_arcieri_treviglio.xlsx)
Here a sample excel you can use with the code

**Comment by catamphetamine** [comment]
FYI:
In the latest version there's `transformData(data)` option which can be used to return transformed "raw" data which is later used in `convertToJson()`.

```js
import readXlsxFile from 'read-excel-file'

readXlsxFile(file, {
  schema,
  transformData(data) {
    return data
  }
})
```

**Comment by andreanta** [comment]
Thanks for support, i'm sorry but i'll try this way, but no log, 
can you write a simple sample :-)


	```
const righeExcel = [];
			await readXlsxFile(filePath, {
				schema,
				transformData(data) {
					data.forEach(element => {
						console.log(element);
					});
					return data;
				},
			}).then(({ rows, errors }) => {
				for (const element of errors) {
					// console.log(element);
				}
				rows.forEach(element => {
					righeExcel.push(element);
				});
			});

```

**Comment by catamphetamine** [comment]
All samples are in the README.

**Comment by andreanta** [comment]
This is a new feature you just add, 
i already use succesfully the library to read other excel file with jsno schema like readme sample. 
i'll continue to try to understand how to use new feature.
TIA
Andrea
