### ISSUE TITLE
Unzipper version is affected by npm  security advisory 886

### ISSUE THREAD

**Issue by Dchamard** [catamphetamine/read-excel-file#28]
Unzipper 0.9.15 contains the fix.
@catamphetamine

**Comment by catamphetamine** [comment]
Will update when they publish a migration guide.
https://github.com/ZJONSSON/node-unzipper/issues/130

**Comment by catamphetamine** [comment]
Whatever, seems to work.
Released `read-excel-file@3.0.2`.

**Comment by Dchamard** [comment]
Thanks!
