### ISSUE TITLE
Feature request: read from buffer

### ISSUE THREAD

**Issue by zardilior** [catamphetamine/read-excel-file#30]
When passing a buffer, the following is given as error:
`
TypeError [ERR_INVALID_ARG_VALUE]: The argument 'path' must be a string or Uint8Array without null bytes. Received <Buffer 50 4b 03 04 14 00 06 00 08 00 00 00 21 00 21 8c 46 3a 73 01 00 00 8c 05 00 00 13 00 08 02 5b 43 6f 6e 74 65 6e 74 5f 54`

**Comment by catamphetamine** [comment]
Why would someone need to read from `Buffer` instead of a `Stream`.

**Comment by catamphetamine** [comment]
https://stackoverflow.com/questions/47089230/how-to-convert-buffer-to-stream-in-nodejs

**Comment by zardilior** [comment]
Thanks @catamphetamine

**Comment by zardilior** [comment]
I am trying to read from a file being uploaded

**Comment by catamphetamine** [comment]
Files are usually uploaded into a file in `/tmp/` directory.
If your application reads files being uploaded as `Buffer`s then it's prone to memory overflow attack.

**Comment by zardilior** [comment]
So its better as most sites recommend to wait for the upload to end? And I guess you are saying I should add a size validation?

**Comment by zardilior** [comment]
Max size

**Comment by catamphetamine** [comment]
Consider Express.js:
https://github.com/expressjs/multer#memorystorage
They explicitly say:

> When using memory storage, the file info will contain a field called buffer that contains the entire file.

> WARNING: Uploading very large files, or relatively small files in large numbers very quickly, can cause your application to run out of memory when memory storage is used.

**Comment by zardilior** [comment]
@catamphetamine so the best is not to read from memory but to save it as it uploads and then read from there?

**Comment by catamphetamine** [comment]
@zardilior For a production website like Facebook — of course. For a small demo website a simple Buffer will do. Seems like you're using some in-house HTTP parsing library because all popular libraries use streams.

**Comment by zardilior** [comment]
@catamphetamine I am using multer, maybe not using it well could be

**Comment by catamphetamine** [comment]
Well, I guess for production websites with many users `DiskStorage` should be configured:
https://www.npmjs.com/package/multer#diskstorage
For small or non-public projects `MemoryStorage` would be ok.

**Comment by zardilior** [comment]
@catamphetamine the reason why DiskStorage is not used is because cloud environments like GCP's cloud engine lack hard disks outside of buckets and so. A size validation, if it is possible, shoiuld be added, to stop the overflows you were specifying I guess or what do you think?

**Comment by zardilior** [comment]
Wait I've just seen there is a multer-google-storage nvm

**Comment by catamphetamine** [comment]
> @catamphetamine the reason why DiskStorage is not used is because cloud environments like GCP's cloud engine lack hard disks outside of buckets and so. A size validation, if it is possible, shoiuld be added, to stop the overflows you were specifying I guess or what do you think?

I see.
Well, in AWS it's always "upload to s3 first and then get a ReadableStream" because AWS limits the POST body size to about 6 MB.
https://stackoverflow.com/questions/46358922/request-payload-limit-with-aws-api-gateway

Maybe I could add `Buffer` support in some future if there're many request for such feature but I don't think that would be the case.

```js
const { Readable } = require('stream');

/**
 * @param binary Buffer
 * returns readableInstanceStream Readable
 */
function bufferToStream(binary) {
  return new Readable({
    read() {
      this.push(binary)
      this.push(null)
    }
  })
}
```

**Comment by zardilior** [comment]
yes I believe upload first and read form stream afterwards is the way to go, even in cloud
