### ISSUE TITLE
Allow reading just header

### ISSUE THREAD

**Issue by mokkymiah** [catamphetamine/read-excel-file#31]
I am processing large files and I need to be able to validate the headers before deciding if I want to process the whole file.

**Comment by catamphetamine** [comment]
Describe in more details the exact issue you're having

**Comment by mokkymiah** [comment]
@catamphetamine I want to read just the first row. Right now I have a file that contains near 50,000 rows. However I want to just read the first now.

**Comment by catamphetamine** [comment]
Why do you want to read just the first row.

**Comment by mokkymiah** [comment]
@catamphetamine I want to validate that the given file contains the correct column headers based on my application requirements. The column headers are in the first row.

**Comment by catamphetamine** [comment]
@mokkymiah Why don't you want to read the whole file?

**Comment by mokkymiah** [comment]
@catamphetamine I want to only read the whole file if the columns headers are valid first. This is the application requirement.

**Comment by catamphetamine** [comment]
@mokkymiah 
>  I want to only read the whole file if the columns headers are valid first. This is the application requirement.

Why does the application require not reading the whole file.

**Comment by mokkymiah** [comment]
@catamphetamine  Performance, users provide large files which need to be validated before we can process.

**Comment by catamphetamine** [comment]
@mokkymiah You can provide a detailed use case when reading the whole file is not desireable.

**Comment by catamphetamine** [comment]
I guess we could say that this library won't have such a feature.
