### ISSUE TITLE
Reading certain files while not reading all excel files

### ISSUE THREAD

**Issue by shreyansh-goyal** [catamphetamine/read-excel-file#33]
It is parsing some excel file while showing different type of errors corresponding to the different types of files

**Comment by shreyansh-goyal** [comment]
Not able to read the large files

**Comment by catamphetamine** [comment]
Provide the file

**Comment by shreyansh-goyal** [comment]
Unhandled rejection Error: invalid signature: 0x7473614d

**Comment by shreyansh-goyal** [comment]
(node:5722) UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded

**Comment by shreyansh-goyal** [comment]
Although I am using the streams

**Comment by catamphetamine** [comment]
Closing until the file is provided.

**Comment by christiaanwesterbeek** [comment]
Related: https://github.com/catamphetamine/read-excel-file/issues/38
