### ISSUE TITLE
import xlsx file after exporting error

### ISSUE THREAD

**Issue by TienRyo** [catamphetamine/read-excel-file#36]
![image](https://user-images.githubusercontent.com/36028064/63143043-9ef23e00-c016-11e9-8d3c-3fdecb433c70.png)`

**Comment by catamphetamine** [comment]
Attach the file

**Comment by TienRyo** [comment]
@catamphetamine Please help find solutions.

**Comment by TienRyo** [comment]
When I export the xlsx file from the XLSX library. I import the file with read-excel-file then report the error.
