### ISSUE TITLE
Formula to string conversion

### ISSUE THREAD

**Issue by sanghaiadarsh** [catamphetamine/read-excel-file#39]
When the excel value is set as a formula linking to another cell, the library expects the formula to convert to a number. But in case the formula converts to a string the library reads it as a NaN value rather than string. 

- example:
--- cell A1 -> =A2
--- cell A2 -> "Test String"
Now when the library reads A1 it converts the formula and expects a number, but it gets "Test String". This is read as NaN and is an issue.

**Comment by catamphetamine** [comment]
Hello.
Formulas are not supported in this library:
https://github.com/catamphetamine/read-excel-file#gotchas
They only work sometimes when there's a pre-calculated value, otherwise it's `null`.
