### ISSUE TITLE
File size to big issue

### ISSUE THREAD

**Issue by divanvb** [catamphetamine/read-excel-file#4]
Hi

I'm having trouble reading a bigger xlsx file.

Reading one that is +-35KB in size works.
Reading files with size 1.1MB & 800KB keeps giving me this error:

> Error: ENOENT: no such file or directory, open 'MSISDN_SIT.xlsx'

Any idea what could be happening?

**Comment by catamphetamine** [comment]
Where are you reading the file: on backend or in a browser?

**Comment by divanvb** [comment]
I'm reading it in the backend. I've noticed it now works but it's struggling to process an excel file with many rows. I get the following error:

> RangeError: Maximum call stack size exceeded

**Comment by catamphetamine** [comment]
If you make up a sample repo with the file and the instructions then I could have a look.

**Comment by divanvb** [comment]
The thing is, the file is confidential (work basis) so I can't share it, unfortunately. But I can share the code snippets with you.

`req.files[''].mv(path + req.files[''].name, err => {
				readXlsxFile(path + req.files[''].name, {
					schema,
				}).then(({ rows, errors }) => {
					console.log(errors);
					res.send(rows);
				});
			});`

**Comment by divanvb** [comment]
@catamphetamine  The spreadsheet has over 20k rows FYI.

**Comment by hnguyen48206** [comment]
I'm having the same issue too. My files are generally around 3-4MB each and the plugin just got frozen.

**Comment by heavensloop** [comment]
Any fix to this yet?

**Comment by catamphetamine** [comment]
> Any fix to this yet?

No fix for freezing because that's some JS.Zip issue.
Any other errors — provide a file.

**Comment by catamphetamine** [comment]
I fixed `"RangeError: Maximum call stack size exceeded"` for server-side code today.
See if the latest version fixes the issue.
If it doesn't then post the error stack trace and the Excel file.

**Comment by heavensloop** [comment]
> I fixed `"RangeError: Maximum call stack size exceeded"` for server-side code today.
> See if the latest version fixes the issue.
> If it doesn't then post the error stack trace and the Excel file.

I appreciate your efforts. will check and revert.

**Comment by catamphetamine** [comment]
@heavensloop Yeah, I discovered the bug when applied the fix for IE11:
https://github.com/catamphetamine/read-excel-file/issues/26
If you have already migrated from this library to some other library then there's no need to check if the fix works because I have tested it too and it worked.

**Comment by anamika-yadav** [comment]
Hi I am facing the same issue. Getting this error RangeError: Maximum call stack size exceeded.
I have used the latest version which is 4.0.1.

**Comment by catamphetamine** [comment]
@anamika-yadav Provide the file.

**Comment by anamika-yadav** [comment]
I cannot provide the file as it contains sensitive data. I can share the format of file. It contains 5 columns and has 44567 rows. The maximum no of rows that it can process in 20K. If there is more than that it breaks and give RangeError: Maximum call stack size exceeded error.

**Comment by christiaanwesterbeek** [comment]
I file is provided in another issue that is causing this error: https://github.com/catamphetamine/read-excel-file/issues/38
