### ISSUE TITLE
Customize required/invalid error message

### ISSUE THREAD

**Issue by mattixittam** [catamphetamine/read-excel-file#44]
I would like to throw a custom error message when the required validator or the type validator returns false.

I figured I could use the `validate` or `parse` functions, but these don't seem to get called for empty cells.

So if I could customize the error messages for the built in validators I would be so happy :)

**Comment by catamphetamine** [comment]
Hi.
The error messages are not meant to be output to the user directly.
Instead, inspect the `errors` property and generate your own messages, don't just do `JSON.stringify(errors)` if you want custom messages.
