### ISSUE TITLE
Get NaN when string value from a formula

### ISSUE THREAD

**Issue by celestialkylin** [catamphetamine/read-excel-file#45]
I have a cell, the value is string concat from other cells. When I parse this file I get NaN in this cell. I try add some code in function Cell

case 's':
      value = values[parseInt(value)].trim();
      if (value === '') {
        value = undefined;
      }
      break;

    case 'str':
      value = value.trim();
      if (value === '') {
        value = undefined;
      }
      break;

and solved it, maybe it's a problem.

**Comment by celestialkylin** [comment]
Why doesn't support? the formula result is place in the <v> tag already.  If the formula result is number type, this library can get it correct. If string type, get NaN. The code I provide can solved this problem.

**Comment by catamphetamine** [comment]
You should practice your English more

**Comment by celestialkylin** [comment]
yeap, I apologize for my poor English.

**Comment by catamphetamine** [comment]
> the formula result is placed in the `v` tag already.
Post the piece of your XML where `v` tag is set for the column you described.

> If the formula result is number type, this library can get it correct.
Yes.
Because in XLSX files **all** strings are not strings and are numbers instead: the number is the key in the strings dictionary.

**Comment by celestialkylin** [comment]
I use libreoffice, and wps, they both have the result. the piece below: 
`<row r="7" customFormat="false" ht="13.5" hidden="false" customHeight="false" outlineLevel="0" collapsed="false"><c r="B7" s="0" t="str"><f aca="false">_xlfn.CONCAT(C5,D5)</f><v>Value2Value3</v></c><c r="C7" s="0" t="n"><f aca="false">SIN(F1)</f><v>0.909297426825682</v></c><c r="D7" s="0" t="s"><v>16</v></c><c r="E7" s="0" t="s"><v>17</v></c><c r="F7" s="0" t="s"><v>18</v></c></row>`

cell C5 value is 'Value2', cell D5 value is 'Value3', concat to B7 equal Value2Value3.

**Comment by catamphetamine** [comment]
Provide the sample file file and post a screenshot of its data in the Excel software.

**Comment by celestialkylin** [comment]
![image](https://user-images.githubusercontent.com/17632933/66647717-3c0ad500-ec5c-11e9-83db-d95a9b31b38a.png)

[test.xlsx](https://github.com/catamphetamine/read-excel-file/files/3717223/test.xlsx)

**Comment by catamphetamine** [comment]
Released `read-excel-file@4.0.3`.
