### ISSUE TITLE
Is this module supports xls files ? 

### ISSUE THREAD

**Issue by shubhv1** [catamphetamine/read-excel-file#46]
Simple xls are supporting but complex like along with spreadsheets are not supported. 
Giving me this error
Uncaught (in promise) TypeError: Cannot read property 'nodeType' of undefined
    at Function.push../node_modules/xpath/xpath.js.PathExpr.getRoot (xpath.js:1448)
    at

**Comment by catamphetamine** [comment]
This module doesn't support XLS files.
The module name might be misleading but that's how it was originally called.

**Comment by shubhv1** [comment]
Thanks for the response.
Then how to handle error? Like I want to show error if there is any error or file format is wrong.

**Comment by catamphetamine** [comment]
I guess the only way is checking file extension when a user selects the file in their browser (or check file path in Node.js).
