### ISSUE TITLE
Allow schema skipping columns

### ISSUE THREAD

**Issue by llermaly** [catamphetamine/read-excel-file#48]
Hello, 

I'm receiving a 10 columns file but I only need 5. Is there a way to tell the schema to skip the unwanted columns? If I only put in the schema the columns I need the json response is empty.

Thanks!

**Comment by catamphetamine** [comment]
To skip certain columns omit them in schema.

**Comment by llermaly** [comment]
hello @catamphetamine  and thanks, if I omit columns then I get this response: 

{ rows: [], errors: [] }

**Comment by catamphetamine** [comment]
provide an online demo somewhere on codepen or alternative.

**Comment by llermaly** [comment]
My mistake, the file was wrong. It is working as expected.

Thanks for your time
