### ISSUE TITLE
Cannot read property of row

### ISSUE THREAD

**Issue by Wolfleader101** [catamphetamine/read-excel-file#49]
Hello,
 i am trying to get my code working. I want it to be able to read excel document delete empty cells and presentational cells however my code ( which I have just used from the README does not work.
```  readXlsxFile('app/upload/file.xlsx', { 
    schema,
    transformData(data) {
      // Removes empty rows.
      return data.filter(rows => row.filter(column => column !== null).length > 0)
      
    }
  }).then(({ rows, errors }) => {
     console.log(rows)
  })
```

I get error
`(node:23796) UnhandledPromiseRejectionWarning: ReferenceError: row is not defined`

**Comment by catamphetamine** [comment]
Indeed, that was a typo.
Corrected: `return data.filter(row => row.filter`
Updated the readme.

**Comment by Wolfleader101** [comment]
this now returns an empty array
`.then(({ row, errors }) => {
     console.log(row)
  })`

**Comment by catamphetamine** [comment]
If an array is empty then it means there have been no columns parsed.

**Comment by Wolfleader101** [comment]
So what would be my best option in filtering out the first 8 rows?

**Comment by Wolfleader101** [comment]
AS i cant find a way to filter out the first 8 rows that will return a array

**Comment by catamphetamine** [comment]
It's not clear what your case is.
And anyway your case is your own case, so you should figure it out yourself.
I won't be doing it for you.

**Comment by Wolfleader101** [comment]
So i know how to do it but i dont understand on how i i can then console.log the data.

my code ```.then(({ row, errors }) => {
     console.log(row)
  })```
