### ISSUE TITLE
Attempting to specify file path in code instead of using input element

### ISSUE THREAD

**Issue by devnull13** [catamphetamine/read-excel-file#5]
Hello,

First of all thank you for your work with this module, as it proven very helpful to me.
I'm reaching out to you as I used all other alternatives to find a solution to my problem.
Your script is working perfectly when we load an XLSX file using the input html element but since in my project I'll be using always the same file, I wanted to remove the input element and specify in the code what will be the XLSX file.
I've looked for the Blob function and other similar functions but couldn't manage to get it working. 
I'm a newbie coder and I'm sorry for this basic question but got no one else to resort.

Thanks and best regards,

**Comment by devnull13** [comment]
I also tried this:

var f = new File([], 'ONCALL.xlsx', {type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});

The use it in readXlsxFile like this:

readXlsxFile(f, {sheet: 3} ,{ dateFormat: 'MM/DD/YY' }).then(function(data) {
			    // `data` is an array of rows
			    // each row being an array of cells.
				//var dataString = JSON.stringify(data, null, 2)
				
				ranContactData = data
				
			
				document.getElementById('result-table3').innerHTML = '<table>' + data.map(row => '<tr>' + row.map(cell => `<td>${cell === null ? '' : cell}</td>`).join('') + '</tr>').join('') + '</table>'
			  }, (error) => {
			  	console.error(error)
			  	alert("Error while parsing Excel file. See console output for the error stack trace.")
			  })

Still no luck.
Got error on console:
index.html:414 Error: End of data reached (data length = 0, asked index = 4). Corrupted zip ?
    at i.checkIndex (DataReader.js:26)
    at i.checkOffset (DataReader.js:17)
    at i.readData (Uint8ArrayReader.js:13)
    at i.readString (DataReader.js:75)
    at u.isSignature (zipEntries.js:40)
    at u.readEndOfCentral (zipEntries.js:165)
    at u.load (zipEntries.js:256)
    at load.js:49
readXlsxFile.then @ index.html:414
Promise.then (async)
(anonymous) @ index.html:404

**Comment by catamphetamine** [comment]
So you will be reading a file from the same path daily in a browser?

**Comment by catamphetamine** [comment]
Well, this library uses `jszip` internally and it calls `JSZip.loadAsync(file)` where `file` is the `file` that's being passed to the read xlsx function.
So if `jszip` doesn't understand the file you're passing then you should consult `jszip` docs.
https://stuk.github.io/jszip/documentation/api_jszip/load_async.html
https://github.com/catamphetamine/read-excel-file/blob/master/source/unpackXlsxFileBrowser.js

**Comment by devnull13** [comment]
Thanks for your help
