### ISSUE TITLE
[error handle] for no such file or directory

### ISSUE THREAD

**Issue by shad0xfox** [catamphetamine/read-excel-file#50]
hello, 

in unpackXlsxFileNode.js file

maybe it should be 

    stream
      .on('error', reject)
      .pipe(unzip.Parse())
      .on('error', reject)
      ....

for  'no such file or directory'  error handle

thank you very much

**Comment by catamphetamine** [comment]
Have you checked that it works?

**Comment by catamphetamine** [comment]
Released `read-excel-file@4.0.4`.
