### ISSUE TITLE
(Fixed) (JSZip bug) IE11 Error "Invalid object called"

### ISSUE THREAD

**Issue by 54mu3l** [catamphetamine/read-excel-file#54]
This simple line dosn't work in IE11 / Edge:

`let data = await readXlsxFile(file, { sheet: 2 });`

After some research I found the reason for that is jszip (version 3.2.2).
As soon as I downgraded to jszip version 3.1.5 it worked great again.

It probably has something to do with the following jszip issue: [https://github.com/Stuk/jszip/issues/630](https://github.com/Stuk/jszip/issues/630)

Can anyone confirm/resolve this issue?

**Comment by stylefieber** [comment]
Confirmed

**Comment by catamphetamine** [comment]
Oh well, we'll set the `3.1.5` version in `package.json` then until they fix it.
It has been 30 days in the original issue and still none of the maintainers of `JSZip` answered: perhaps it's not being actively maintained anymore.

Published `read-excel-file@4.0.5`.

**Comment by catamphetamine** [comment]
It has been requested to update `jszip` to the latest version:
https://gitlab.com/catamphetamine/read-excel-file/-/issues/8

Updated in `read-excel-file@4.0.8`. We'll see if anyone reports anything.
Seems to work in IE11 on my machine, even with `jszip@3.2.2`.
