### ISSUE TITLE
Read Row & Column Data

### ISSUE THREAD

**Issue by DoraTheCodeExplorer-1337** [catamphetamine/read-excel-file#56]
Hello,

How do you read the column data from a specific cell. I want to get all the cells that start with ABC. I then want to get each of their column data. For example there might be cells:
ABC3943, ABC9438, ABC1823.
How do i pass this through the schema and get there data?

**Comment by DoraTheCodeExplorer-1337** [comment]
Hello,

How do you read the column data from a specific cell. I want to get all the cells that start with ABC. I then want to get each of their column data. For example there might be cells:
ABC3943, ABC9438, ABC1823.
How do i pass this through the schema and get there data?

**Comment by catamphetamine** [comment]
Hi.
There's no such possibility in this library.
For reading cell-by-cell you can use any other library like `xlsx`.
https://github.com/catamphetamine/read-excel-file/issues/38#issuecomment-544286628

**Comment by DoraTheCodeExplorer-1337** [comment]
So i cannot read individual cells rows? OK thank you :D

**Comment by bigabdoul** [comment]
> Hello,
> 
> How do you read the column data from a specific cell. I want to get all the cells that start with ABC. I then want to get each of their column data. For example there might be cells:
> ABC3943, ABC9438, ABC1823.
> How do i pass this through the schema and get there data?

Try out https://www.npmjs.com/package/fast-xlsx-reader
