### ISSUE TITLE
parse validation using async function

### ISSUE THREAD

**Issue by llermaly** [catamphetamine/read-excel-file#57]
Hello, is it possible to validate rows using an async function (like consulting database) and what is the best way to do it? I'm trying without success.

```
    parse(value) {
      const exists = findInDatabase(value) //async
      if (!exists) {
        throw new Error("Error");
      }
      return value;
    }
```

**Comment by catamphetamine** [comment]
> Hello, is it possible to validate rows using an async function (like consulting database)

No.

> what is the best way to do it?

Nothing special about that: first read the data from a file and then validate it as a separate function call.
