### ISSUE TITLE
Column parse method not get undefined value

### ISSUE THREAD

**Issue by Fi1osof** [catamphetamine/read-excel-file#60]
I create schema with field:
```  ID: {
    prop: 'id',
    parse: (value) => {

      console.log('ID cell', value);

      return value;
    },
  },
```
And import file with data:
```

ID | Name
-- | --
ck24yipuq01mu0775gc7i8xf5 | Value 1
ck24yipuq01mv0775411658v5 | Value 2
  | New Value 3
  | New value 4

```

2 rows for update and 2 for insert new data.

I got just 2 validations:
ID cell ck24yipuq01mu0775gc7i8xf5
ID cell ck24yipuq01mv0775411658v5

and do not get 2 rows with id undefined or null. In this case i can not be sure that column ID exists.
I undestand, that i can get first record and check id field exists, but this not validated.

UPD.
< I undestand, that i can get first record and check id field exists, but this not validated.
I cant do this, if no one row have ID value.

**Comment by Fi1osof** [comment]
UPD: i can handle column via transformData
```
readXlsxFile(stream, {
        schema: this.schema,
        transformData: (data) => {
          if (!data || !data[0] || data[0].indexOf('ID') === -1) {
            throw new Error('Column ID required');
          }
          return data;
        },
      });
```

**Comment by catamphetamine** [comment]
`parse` is only called when a cell is not empty.
If a cell value is required, there's `required: true` property.
