### ISSUE TITLE
Parse don't work with not typical types

### ISSUE THREAD

**Issue by Nolarok** [catamphetamine/read-excel-file#61]
I have the next schema:

<pre>const schema = {
'Guest': {
    prop: 'name',
    type: Array,
    parse(value) {
      console.log('parse - guest')
      return value.split('\n')
    }
  },
 'Contacts': {
    prop: 'contacts',
    type: {
      'Phone': {
        prop: 'phone',
        type: String,
      },
      'Email': {
        prop: 'email',
        type: String,
      },
    },
    parse(value) {
      console.log('parse - contacts')
      return [value.phone, value.email]
    }
  },
}
</pre>
The parse method does not work with columns that do not have a base type. Console.log don't call for 'Contacts' column.

**Comment by catamphetamine** [comment]
> The parse method does not work with columns that do not have a base type.

It's not supposed to.
See the README example: `CONTACT` is not a column in an Excel file there.
