### ISSUE TITLE
Rows and errors return undefined values using schema to convert data in json

### ISSUE THREAD

**Issue by Lysiah** [catamphetamine/read-excel-file#65]
Hi!

I tried to use a schema to transform excel data in json as stated in the documentation, but rows and errors return `undefined` value.

```js
readXlsxFile(file, { schema }).then(({ rows, errors }) => {
  // `errors` have shape `{ row, column, error, value }`.
  errors.length === 0

  rows === [{
    date: new Date(2018, 2, 24),
    numberOfStudents: 123,
    course: {
      isFree: true,
      title: 'Chemistry'
    },
    contact: '+11234567890',
  }]
})
```

Does anyone have the same problem I do?

**Comment by catamphetamine** [comment]
You can put up an online demo if you want someone to look at it.

**Comment by Lysiah** [comment]
Damn it! It was a mistake on my part on `schema` key. Sorry for the inconvenience, it works perfectly, thanks :)

**Comment by Dynamis-d-Arc** [comment]
> Damn it! It was a mistake on my part on `schema` key. Sorry for the inconvenience, it works perfectly, thanks :)

Hi, can you share what was the mistake? Because I am also in the same situation as you now... Thanks
