### ISSUE TITLE
(Performance) Limit the number of rows being read for huge datasets

### ISSUE THREAD

**Issue by freinet12** [catamphetamine/read-excel-file#69]
How can I set a limit to the number rows to read? like set a max number of rows because it reads the entire file, and if the file is huge, it will lead to memory issues.

**Comment by catamphetamine** [comment]
Yes, perhaps I should even add it to the readme as the first paragraph: FOR SMALL FILES ONLY.
There have been numerous complaints about the parsing time.
What number of rows is comfortable in your case?
At what number of rows do you consider a file "huge" and how much seconds long is the freezing?

**Comment by freinet12** [comment]
I only need to read the first 10 rows in order to generate a file preview in the UI in my case. So I have no control over the files that the clients are uploading, which means they can be uploading files with 100k+ rows of data. So setting a limit would avoid potential memory issues

**Comment by catamphetamine** [comment]
Since it's a DOM parser, not SAX parser, it parses the whole XML file.
A SAX parser would most likely fix the RAM overflow.
How much RAM does it use in you case? For file with how many rows and columns?
