### ISSUE TITLE
unable to parse time properly (00:22:12) .

### ISSUE THREAD

**Issue by rjdugar** [catamphetamine/read-excel-file#70]
My excel sheet has value in format hh:mm:ss but while converting it to JSON this value is converted in date format.

I need the value in JSON to be same .

**Comment by catamphetamine** [comment]
How would you imagine that.
If a cell type is date or time, it's converted to date or time automatically.
There's no option to disable it in the code.

**Comment by rjdugar** [comment]
But in case of time, it's not able to convert it.
for example -- **00:22:12** is converted to Date object  having value -- **1899-12-30T12:42:48.000Z**

**Comment by catamphetamine** [comment]
Provide the file and I can take a look

**Comment by techie-cloud** [comment]
i have same issue.my time in 12:16 PM and i is parsing it as "1899-12-31T00:16:00.000Z" which on conversion is "4:44:12 AM".

**Comment by rjdugar** [comment]
use Xls-json-parser

**Comment by rjdugar** [comment]
> i have same issue.my time in 12:16 PM and i is parsing it as "1899-12-31T00:16:00.000Z" which on conversion is "4:44:12 AM".

Xls-json-parser

**Comment by catamphetamine** [comment]
Closing since no file has been provided.

**Comment by andreieuganox** [comment]
Still valid
