### ISSUE TITLE
How to read the special character (plus symbol) from Excel Spreadsheet

### ISSUE THREAD

**Issue by ramya-sc** [catamphetamine/read-excel-file#75]
Hi,
Assume ,  I have excel rows, something like below, 
[
![image](https://user-images.githubusercontent.com/47598314/77227204-7f228a00-6ba4-11ea-89a0-33ca947befb9.png)
](url)
If I try to read phone number  +11234567890 , plus symbol is missing in  UI or in console data .
Can you please suggest me on this ? 
Thanks.

**Comment by catamphetamine** [comment]
Provide the file

**Comment by ramya-sc** [comment]
@catamphetamine , please find the below excel file.

[
[Demo_sheet.xlsx](https://github.com/catamphetamine/read-excel-file/files/4365885/Demo_sheet.xlsx)
](url)

**Comment by catamphetamine** [comment]
The content of the cells is without `+`, so the library behaves correctly.
The output format of the cells is "Custom": `\+0;`.

![image](https://user-images.githubusercontent.com/477167/77258948-09471d00-6c8f-11ea-9a7a-56a02b695ae7.png)

Users are supposed to define their own formats for Excel data:
https://support.office.com/en-us/article/display-numbers-as-phone-numbers-7feabe49-15b3-411c-a030-781b4f2c87dd
https://www.youtube.com/watch?v=dMNmrTHWosQ

So in your case you should prepend the `+` after parsing cell values.
