### ISSUE TITLE
Empty cell skipped

### ISSUE THREAD

**Issue by kevingatp** [catamphetamine/read-excel-file#76]
Hi Nikolay,

Thankyou for this awesome library, i've used this library twice. But I just realize this:
If I have excel like this:

name | age
-- | --
Abed |  
Bern | 21

it will return as:
`[{
name: 'Abed'
},
{
name: 'Bern',
age: 21
}]`

it's skip the empty cell, I also have add `required: true` in schema, but nothing happen.
I need these attribute even it has no value/data. How can I do that?
Thanks

**Comment by catamphetamine** [comment]
Hi.
By default, all empty cells are skipped.
If a cell was marked as `required: true`, then it would throw an error.
You can post your schema.
