### ISSUE TITLE
rowIndex is missing in successful rows

### ISSUE THREAD

**Issue by ramya-sc** [catamphetamine/read-excel-file#77]
Hi, 
[
[sample_sheet.xlsx](https://github.com/catamphetamine/read-excel-file/files/4373534/sample_sheet.xlsx)
](url)
,
 `  readXlsxFile(this.fileToUpload, {
         schema, 
         transformData(data, ) {
          // read the excel sheet from row 1
           for (let i = 1; i < data.length; i++) {  
            let result = data[i]
            if (result) {
             results.push(result)
            }
          }
          return results;
            // return  data.filter(row => row.filter(column => column !== null).length > 0)
         }  
      }).then(({ rows, errors,  }) => { console.log(rows) }`
![image](https://user-images.githubusercontent.com/47598314/77395425-8c6b8e80-6dc7-11ea-801e-899cc8a3de0d.png)

Is it possible to add **row_Index** to above **rows** (attached image) ? ,
 
Like how we are getting **row_Index** in **errors** [ 
![image](https://user-images.githubusercontent.com/47598314/77395695-26333b80-6dc8-11ea-9d06-06488de316eb.png) ]

 using :  "read-excel-file": "^4.0.6",

**Comment by catamphetamine** [comment]
Hi.
Why would you want to have row index in rows?
The answer is short: anything is possible, but such feature doesn't make any sense.

**Comment by ramya-sc** [comment]
Because, 
Assume, below are the **successful rows** what I am getting from excel , let it be **array1** ,
![image](https://user-images.githubusercontent.com/47598314/77500691-d7df7480-6e7b-11ea-9469-bf785774636a.png)

and I formatted the **errors** arrays something like below according to my requirement, let it be **array2**,
![image](https://user-images.githubusercontent.com/47598314/77500983-9b604880-6e7c-11ea-9eb0-dc27d3e2ee71.png)


and I need to form a **newArray** like below by looping through **array1** and **array2**

`[ {row: 1, firstName: null,  lastName: null,  phoneNo: 123,  emailId: null },
  {row: 2, firstName: "Ramya", lastName: "f", phoneNo: null, emailId: "ramy" },
  {row: 3, firstName: null,  lastName: "k" , phoneNo: null, emailId: null },
  {row :4 , firstName: "Divya", lastName: "h", phoneNo: 1234567890, emailId: "divya@gmail.com" },
  {row :5 , firstName: "Jhon" , lastName: null,  phoneNo: null, emailId: null },
  { row:6 , firstName: null, lastName: "a", phoneNo: null, emailId: null }
]
 `
As, there is no key called **row** in **array1** , I am facing difficultly to loop an  array1 and array2, 
so, I am requesting you to please add rowIndex for the successful rows.
Thanks.

**Comment by catamphetamine** [comment]
> So, I am requesting you to please add rowIndex for the successful rows.

No features would be added.
But, you can fork the project and add any features.

**Comment by catamphetamine** [comment]
I'll close this one.
