### ISSUE TITLE
Cell value coming back wrong

### ISSUE THREAD

**Issue by patgaddis** [catamphetamine/read-excel-file#8]
I've got a column in a xlsx file where the value of each cell is the result of a lookup function pointing to another sheet. When opened in Excel, this column shows the strings returned from the other sheet. However, when I read the file with read-excel-file, I'm getting back what looks to be the string value that I'm seeing in Excel, but converted to a number (ie, if the string starts with "61bkld", I'm getting 61; essentially every number at the beginning of the string, and NaN when the string starts with a letter). Is it possible that the lookup function in these cells is throwing off read-excel-file because of something to do with the cell type? Just trying to figure it why it wants to convert these particular values to numbers... any help would be greatly appreciated!

**Comment by catamphetamine** [comment]
It autodetects excel column types and converts numbers to number.
You can post the XLSX file along with screenshots and instructions if you want.

**Comment by patgaddis** [comment]
Because of the business nature of the spreadsheet, I unfortunately can't post the whole spreadsheet itself. However, I can post some sample data to help better explain what I'm seeing.

There are 2 sheets involved; On the first sheet ("sheet 1"), there are 2 columns (call them, "GUID-1" and "GUID-2") that are just static text. Each row represents a relationship between GUID-1 and GUID-2. On the second sheet ("sheet 2"), there are also 2 columns. The first column are values that match values in the GUID-1 column on sheet 1. The second column is set to a lookup function that references sheet 1 and does a lookup for the value in GUID-1 on sheet 1 based on matching its first column on sheet 2 to GUID-2 on sheet 1.

A few examples of what I'm seeing from read-excel-file:

If the value returned by the lookup function is "0b147a82-510a-4f2a-825c-01439aa923e5", the row array returned by read-excel-file has the numeric value 0.

If the value returned by the lookup function is "61c47a82-510a-4f2a-825c-01439aa923e5", the row array returned by read-excel-file has the numeric value 61.

If the value returned by the lookup function starts with anything other than a number, the row array returned by read-excel-file has NaN instead of a number.

The column on sheet 2 that has the lookup function looks like this:

=VLOOKUP(D74,'ID Relationships'!$A$1:$B$1600,2,FALSE)


I tried setting the format of the cells in the lookup column to Text, as well as setting the format of both cells in sheet 1 to Text, but that doesn't appear to have changed anything.


If you've got this far, thanks! Any ideas?

**Comment by catamphetamine** [comment]
I see.
Well, I guess that's too complex of a use case.
You can create a completely new Excel file and re-enter data there (don't copy-and-paste it because it will copy formatting).
Anyway, I guess your input Excel files are just too complex for this library: it doesn't support functions or something like that, it only supports plain values.

**Comment by catamphetamine** [comment]
The use case for which this library was written is people having a simplest possible way of supplying input data for an app.
Event "Export as CSV" is too complex for them.
So that's the main use case for this library.

**Comment by patgaddis** [comment]
Totally understood.

I'm going to do a little digging and see if I can't fix it myself somehow. It sure seems like read-excel-file is getting the proper GUID string back from the lookup function; it is just erroneously trying to convert it to a number. It sure feels fixable without too much work, but I guess I won't know until I get in there.

Either way, thanks for your help!

**Comment by sonaba** [comment]
> I see.
> 
> If you will be experimenting with the code in `commonjs` folder (Node.js) then you can look into this code I guess:
> https://github.com/catamphetamine/read-excel-file/blob/366964493e94a441e5f0ca179bc57925da5d6ad4/source/readXlsx.js#L158
> 
> It says:
> 
> ```js
>     case 'n':
>     // Default type is "n".
>     // http://www.datypic.com/sc/ooxml/t-ssml_CT_Cell.html
>     default:
>       if (value === undefined) {
>         break
>       }
>       value = parseFloat(value)
> ```
> 
> So I guess there can be an extra "computed via a function" type or something else, which doesn't have a `case` in that `switch` and that could be causing your issue.
> You could `console.log(cellNode.getAttribute('t'))` to see the exact cell type and look it up in the reference.
> http://webapp.docx4java.org/OnlineDemo/ecma376/SpreadsheetML/ST_CellType.html

according to the page u linked there is an 'str' type for 'formula' string so us should correct this in type check:
`// http://webapp.docx4java.org/OnlineDemo/ecma376/SpreadsheetML/ST_CellType.html  
  switch (cellNode.getAttribute('t')) {
    case 's':
      value = values[parseInt(value)].trim();      
      if (value === '') {
        value = undefined;
      }
      break;
      
    case 'str':
      value = value.trim();
      if (value === '') {
        value = undefined;
      }
      break;

    case 'b':
      value = value === '1' ? true : false;
      break;

    case 'n':
    // Default type is "n".
    // http://www.datypic.com/sc/ooxml/t-ssml_CT_Cell.html
    default:
      if (value === undefined) {
        break;
      }
      value = parseFloat(value);
      // XLSX has no specific format for dates.
      // Sometimes a date can be heuristically detected.
      // https://github.com/catamphetamine/read-excel-file/issues/3#issuecomment-395770777
      var style = styles[parseInt(cellNode.getAttribute('s') || 0)];
      if (style.numberFormat.id >= 14 && style.numberFormat.id <= 22 || style.numberFormat.id >= 45 && style.numberFormat.id <= 47 || options.dateFormat && style.numberFormat.template === options.dateFormat || options.smartDateParser !== false && style.numberFormat.template && isDateTemplate(style.numberFormat.template)) {
        value = parseDate(value, properties);
      }
      break;
  }`

**Comment by catamphetamine** [comment]
@sonaba Speak English
