### ISSUE TITLE
Timespan data is converted to a time...

### ISSUE THREAD

**Issue by JieCarolHu** [catamphetamine/read-excel-file#83]
I have a column in my excel file which contains data like `0:02:44` 
However, I read this excel file and this item is read as `Sat Dec 30 1899 04:02:44 GMT-0800 (Pacific Standard Time)` I was wondering if there is a way just get the string value without doing any kind of conversion...

**Comment by catamphetamine** [comment]
Hi.
When you see "0:02:44" in an Excel file editor, it doesn't mean that the actual cell value in the Excel file is "0:02:44". Instead, it's a number "under the hood".
So, what you were asking for is not possible.
One could pass custom `parseDate()` function though:
https://github.com/catamphetamine/read-excel-file/blob/8fbcf33c4c5e850c471498303ea2b49cfeb9a73a/source/readXlsx.js#L199
