### ISSUE TITLE
Error uploading csv file

### ISSUE THREAD

**Issue by luongnv6** [catamphetamine/read-excel-file#84]
Hi all,
When I upload the csv file, I receive the following error.
![image](https://user-images.githubusercontent.com/21300748/88355179-c8baf580-cd8d-11ea-99c7-5d41d8fce5ed.png)

**Comment by catamphetamine** [comment]
Looks like an incorrect *.xlsx file.

**Comment by luongnv6** [comment]
> Looks like an incorrect *.xlsx file.

yes, this is a *.csv file, not xlsx

**Comment by catamphetamine** [comment]
Well, why're you using this library then.
It's for *.xlsx files.
