### ISSUE TITLE
"sharedstrings.xml" file not found in the *.xlsx file

### ISSUE THREAD

**Issue by KzooDrew** [catamphetamine/read-excel-file#85]
The plugin is throwing the following error:  "sharedstrings.xml" file not found in the *.xlsx file.

The Excel file I am using contains a single column of 6-digit numbers for the cell values, no formatting and no formulas.  It's about as basic as it gets.  However,  other such files are able to be parsed.

I can send the file in question via PM if you let me know where you want me to send it.

**Comment by catamphetamine** [comment]
How was the file created? In what editor?

**Comment by catamphetamine** [comment]
I'd say that `xl/sharedStrings.xml` file is required and if it's missing then it's assumed to be a bug.

**Comment by KzooDrew** [comment]
[Random Numbers.xlsx](https://github.com/catamphetamine/read-excel-file/files/5018272/Random.Numbers.xlsx)

I see I can attach files.  This is the file that is causing the error.  The user that generated this file has gone home for the day so I will have to get back to you on the Office version and how it was created tomorrow. (we use two different versions of office)

**Comment by KzooDrew** [comment]
Also,  this is the stack trace of the error:

Uncaught (in promise) Error: "sharedStrings.xml" file not found in the *.xlsx file
    n http://intwebuit/Scripts/plugins/ReadExcelFile/ReadExcelFile.min.js:9
    default http://intwebuit/Scripts/plugins/ReadExcelFile/ReadExcelFile.min.js:9
    default http://intwebuit/Scripts/plugins/ReadExcelFile/ReadExcelFile.min.js:9
    default http://intwebuit/Scripts/plugins/ReadExcelFile/ReadExcelFile.min.js:9
    promise callback*readXlsxFile</e.default http://intwebuit/Scripts/plugins/ReadExcelFile/ReadExcelFile.min.js:9

**Comment by KzooDrew** [comment]
I should also point out that I am using the stand-alone CDN version of the plugin:
https://unpkg.com/read-excel-file@4.x/bundle/read-excel-file.min.js

**Comment by catamphetamine** [comment]
@KzooDrew Ok, seems like `sharedStrings.xml` is actually not required to exist if the file has no strings, only numbers.
I've removed the `sharedStrings.xml` requirement in the latest version.

published `read-excel-file@4.0.7`
