### ISSUE TITLE
Error: "styles.xml" file not found in the *.xlsx file

### ISSUE THREAD

**Issue by goranapivis** [catamphetamine/read-excel-file#88]
I have no idea why I got this error. I just trying to import an xlsx file that I have dl from my CRM.

node index.js
(node:47359) UnhandledPromiseRejectionWarning: Error: "styles.xml" file not found in the *.xlsx file

My simple code:

```
const xlsxFile = require('read-excel-file/node');
 
xlsxFile('./Lagerstatus.xlsx').then((rows) => {
    console.log(rows);
    console.table(rows);
   })
```

**Comment by catamphetamine** [comment]
Where did you get the file from?

**Comment by goranapivis** [comment]
From a Swedish CRM called Hyrma.

**Comment by catamphetamine** [comment]
Looks like it doesn't have `styles.xml` inside (it's a zip archive).

**Comment by goranapivis** [comment]
Yes that it's what the error message says. But I don't normally touch Microsoft stuff, so I do not know why it's missing or why it should have an styles.xml.

Can I just add a fake style file somewhere?

**Comment by goranapivis** [comment]
There is a lot of xml files inside such as [Content_Types].xml and workbook.xml but no styles.xml

**Comment by goranapivis** [comment]
Ok, switching to csv parser instead, so I don't have to depend on Bill! :-)
