### ISSUE TITLE
Read Xlsx file with custom sheet name

### ISSUE THREAD

**Issue by thaddeusm** [catamphetamine/read-excel-file#9]
I am working on an application that would allow users to import data from spreadsheet files generated by another application.  These spreadsheets have a single worksheet with the name 'Course Roster'.  

When trying to read the file, I get the following error:

`Error: Sheet "1" not found in *.xlsx file.
    at readXlsx (/.../node_modules/read-excel-file/commonjs/readXlsx.js:49:11)
    at readXlsxFileContents (/.../node_modules/read-excel-file/commonjs/readXlsxFileContents.js:22:38)
    at /.../node_modules/read-excel-file/commonjs/readXlsxFileNode.js:33:47
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)`

I would appreciate any suggestions.

**Update:**

After doing some additional troubleshooting, I think I have isolated the problem to the file format the other application is using for export.  When I open the originally generated file in Excel and save it, Read Excel File is able to parse it.

**Comment by catamphetamine** [comment]
Added support for reading sheets by names.
https://github.com/catamphetamine/read-excel-file#advanced

**Comment by thaddeusm** [comment]
Thanks!   I'll give it a try.

**Comment by catamphetamine** [comment]
It does

**Comment by lkittyzaa** [comment]
How to make import excel on ReactJS by tools 'read-excel-file'?

I'm a beginner. I think have something is wrong. I try to solve but not work. I bring this code from HTML example. Please help me to know : how to write it in reactJS file. Thank you very much.

```
import readXlsxFile from 'read-excel-file';
import React,{Component} from 'react';
import ReactDOM from 'react-dom';

class App extends Component{

    constructor(props){
        super(props);

        const input = document.getElementById('file');


        input.addEventListener('change', () => {
        readXlsxFile(input.files[0]).then((data) => {
            document.getElementById('dtable').innerHTML = '<table border=1>' + data.map(row => '<tr>' + row.map(cell => `<td>${cell === null ? '' : cell}</td>`).join('') + '</tr>').join('') + '</table>';
        })
        })

    }



    render(){
        return (
            <div>
                <input type="file" id="file" />
                <div id="dtable"></div>
            </div>

        ); 

    }

}

ReactDOM.render(<App />,document.querySelector('#root'));
```

**Comment by catamphetamine** [comment]
@lkittyzaa This library doesn't relate to React in any way so it can be used anywhere without any special handling.
Your React code is wrong and you should study React first.
Your event listener binding is not how it should be done in React.

**Comment by lkittyzaa** [comment]
OK Thank you very much for your kindness
