### ISSUE TITLE
Multiple sheets

### ISSUE THREAD

**Issue by david262929** [catamphetamine/read-excel-file#93]
When need to convert data mutiple sheets parralel. 
As first need to get sheets name, after it for each sheet call parser ( readXlsxFile(file, { sheet: 'eachSheetName' } ) )

Can do that for one call function readXlsxFile.

Example

```
readXlsxFile(file, {
    multipleSheetMode: true,
    config: [
       {
        sheet: 'first sheet',
        schema: schemaOfFirstSheet,
        transformData: () => {}
       },
       {
        sheet: 'second sheet',
        schema: schemaOfSecondSheet,
        transformData: () => {}
       },
    ]
})

```

**Comment by catamphetamine** [comment]
Format your code properly

**Comment by david262929** [comment]
> Format your code properly

done

**Comment by catamphetamine** [comment]
One could read a file sheet-by-sheet.
https://gitlab.com/catamphetamine/read-excel-file#advanced

**Comment by david262929** [comment]
now for do my task i need 
- to get sheets names
- map on returned array and call same function the returned names count

Example: 

```

  const sheets = await readXlsxFile(file, { getSheets: true });
  // sheets === [{ name: 'Sheet1' }, { name: 'Sheet2' }]
  
  sheets.forEach(({ name }) => {
    readXlsxFile(file, { sheet: name }).then((data) => {
      console.log(data)
    })
  })

```

**Comment by catamphetamine** [comment]
Yes

**Comment by david262929** [comment]
but that is heavy task, it can be more optimized

**Comment by catamphetamine** [comment]
It could be.

But I don't want to do that.
