### ISSUE TITLE
Backward compability with v4

### ISSUE THREAD

**Issue by codler** [catamphetamine/read-excel-file#94]
@catamphetamine Hi, could you provide an options in v5 to skip empty lines to make it backward compatible with v4?

**Comment by catamphetamine** [comment]
Hi. Why don’t you simply update to the latest version.

**Comment by codler** [comment]
Yes, i want to use latest version, but it have big breaking changes, by adding the option , in latest version, to make possible to skip empty lines again would solve this

**Comment by catamphetamine** [comment]
What changes exactly are an issue?

**Comment by codler** [comment]
In v5
> readXlsxFile() now doesn't skip empty rows or columns: it only skips empty rows or columns at the end, but not in the beginning and not in the middle as it used to.

**Comment by catamphetamine** [comment]
@codler Oh, I see: there's no option to skip empty rows now.
Can you provide an example of how your Excel file looks like (approximately) and why are there empty rows?

**Comment by catamphetamine** [comment]
@codler See `transformData` function parameter that can remove empty rows:
https://github.com/catamphetamine/read-excel-file#transforming-rowscolumns-before-schema-is-applied

**Comment by codler** [comment]
Seems to work, thank you @catamphetamine !
