### ISSUE TITLE
https://github.com/advisories/GHSA-5fg8-2547-mr8q

### ISSUE THREAD

**Issue by codler** [catamphetamine/read-excel-file#96]
https://github.com/advisories/GHSA-5fg8-2547-mr8q

**Comment by catamphetamine** [comment]
FYI: `0.7.0` is still not available:
https://github.com/xmldom/xmldom/issues/271#issuecomment-900899688

**Comment by catamphetamine** [comment]
Fixed in `read-excel-file@5.2.9`.
